# roles/db/tasks/secure.yml
- name: Crear usuario app con permisos m√≠nimos (ejemplo)
  mysql_user:
    name: appuser
    password: "appPass123"
    priv: "*.*:USAGE"
    host: "%"
  when: db_pkg == "mariadb-server"
